name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Increase file limit
        run: ulimit -n 4096

      - name: Install dependencies
        run: npm install --legacy-peer-deps


      - name: Build project
        run: NODE_OPTIONS=--max-old-space-size=4096 npm run build
        timeout-minutes: 20
